### ISSUE TITLE
run 'xocde-build-server' err

### ISSUE THREAD

**Issue by whileGreatHair** [SolaWing/xcode-build-server#27]
**error:**
Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
find root :/Users/user/Library/Developer/Xcode/DerivedData/{app}-befxrmrzdkuusgfvwcjivakwkmpn
updated buildServer.json

I tried several projects and reported this error.

**Comment by SolaWing** [comment]
can you give a mimimum reproducible project？

**Comment by whileGreatHair** [comment]
Sorry, it doesn't seem to affect usage, I used this command because I wanted to write Swift in VsCode, and now it is available. But you should just create a demo project to reproduce. Because after I first tried it in a demo project, I also got an error when I tried it in my own development project. , but it seems to be just a warning. Sorry, I just started learning Swift and know very little about it.

**Comment by SolaWing** [comment]
`xcode-build-server config` call `xcodebuild -showBuildSettings` to figure out xcode build root dir. since it not affect root output, seems It just a warnninng and does not have any real issue. Also notice, when you use `xcode-build-server config`, you have to build from xcode gui with same scheme since xcode-build-server read output log from xcode gui output logs
